-- CreateTable
CREATE TABLE `AuthKey` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `botId` VARCHAR(191) NOT NULL,
    `keyId` VARCHAR(191) NOT NULL,
    `keyJson` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
